name: Makefile Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test Makefile on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.2', '8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Check Docker
        run: |
          docker version
          docker info

      - name: Run make build
        run: make build PHP_VERSION=${{ matrix.php-version }}

      - name: Run make install
        run: sudo make install PHP_VERSION=${{ matrix.php-version }}

      - name: Run make check (post-install)
        run: make check

      - name: Verify PHP Installation
        run: |
          php -v | grep -q "PHP ${{ matrix.php-version }}"
          echo "✅ PHP version verification passed"

      - name: Verify Composer Installation
        run: |
          composer -V
          echo "✅ Composer verification passed"

      - name: Test PHP CLI
        run: |
          result=$(php -r "echo PHP_VERSION;")
          expected_version=${{ matrix.php-version }}
          
          if [[ "$result" == *"$expected_version"* ]]; then
              echo "✅ PHP CLI test passed"
          else
              echo "❌ PHP CLI test failed (got $result, expected $expected_version)"
              exit 1
          fi
      - name: Test Composer
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p test-composer
          cd test-composer
          composer init \
            --name=test/project \
            --description="Test project" \
            --author="Test <test@example.com>" \
            --type=project \
            --no-interaction
          
          # Verify composer.json was created
          if [ -f "composer.json" ]; then
            echo "✅ Composer initialization test passed"
          else
            echo "❌ Composer initialization test failed"
            exit 1
          fi